apiVersion: v1
kind: Pod
metadata:
  generateName: builder
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 10000000
    image: gcr.io/buildpacks/builder:latest
    imagePullPolicy: Always
    name: builder
    resources: {}
    workingDir: /workspace
    volumeMounts:
    - mountPath: /home/cnb/.docker
      name: dockerconfigjson
  dnsPolicy: ClusterFirst
  preemptionPolicy: PreemptLowerPriority
  schedulerName: default-scheduler
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: dockerconfigjson
    secret:
      secretName: dockerconfigjson