apiVersion: v1
kind: Pod
metadata:
  generateName: builder
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 10000000
    image: ghcr.io/ko-build/ko
    imagePullPolicy: Always
    name: builder
    resources: {}
    workingDir: /workspace
    volumeMounts:
    - mountPath: /root/.docker
      name: dockerconfigjson
  dnsPolicy: ClusterFirst
  preemptionPolicy: PreemptLowerPriority
  schedulerName: default-scheduler
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: dockerconfigjson
    secret:
      secretName: dockerconfigjson
